using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LawPracticeFirm.Models
{
    public class SebiExportToExcelPDF
    {
            public Nullable<int> totRow { get; set; }
            public Nullable<long> rownum { get; set; }
            public string cnrno { get; set; }
            public Nullable<int> IsRevenueCourt { get; set; }
            public string Id { get; set; }
            public Nullable<int> IsDelete { get; set; }
            public string CourtName { get; set; }
            public string OtherCourtName { get; set; }
            public Nullable<System.Guid> firmId { get; set; }
            public Nullable<System.DateTime> odate { get; set; }
            public Nullable<System.DateTime> cdate { get; set; }
            public string Teamlead { get; set; }
            public string cstatus { get; set; }
            public Nullable<System.DateTime> date_time { get; set; }
            public string mname { get; set; }
            public Nullable<System.Guid> firmuser { get; set; }
            public Nullable<System.Guid> matterclientid { get; set; }
            public Nullable<int> IsCompanyAdmin { get; set; }
            public string assignuser { get; set; }
            public Nullable<int> IsSync { get; set; }
            public string UserCaseid { get; set; }
            public string CNRCase { get; set; }
            public Nullable<System.DateTime> CaseFilingDate { get; set; }
            public string PrimaryContactID { get; set; }
            public string PrimaryContactName { get; set; }
            public string TotalCaseTime { get; set; }
            public Nullable<int> oedit { get; set; }
            public Nullable<int> odelete { get; set; }
            public string MatterType { get; set; }
            public string SubjectTypeName { get; set; }
            public string TeamLeadName { get; set; }
            public Nullable<System.DateTime> LastModifyDate { get; set; }
            public string Notes { get; set; }
            public Nullable<System.DateTime> CertifiedCopyAppliedon { get; set; }
            public Nullable<System.DateTime> CertifiedCopyReceivedon { get; set; }
            public string ValuationofSuit { get; set; }
            public string Courtfee { get; set; }
            public string OppositePartyCounselname { get; set; }
            public string OppositePartyCounselemail { get; set; }
            public string OppositePartyCounselphone { get; set; }
            public string CasenumberInternal { get; set; }
            public string IsCourtFeePaid { get; set; }
            public string SubjectType { get; set; }
            public string PoliceStation { get; set; }
            public string FIRNo { get; set; }
            public string CaseType { get; set; }
            public string CaseDetails { get; set; }
            public string mtrno { get; set; }
            public string col1 { get; set; }
            public string col2 { get; set; }
            public string col3 { get; set; }
            public string col4 { get; set; }
            public string col5 { get; set; }
            public string col6 { get; set; }
            public string col7 { get; set; }
            public string col8 { get; set; }
            public string col9 { get; set; }
            public string col10 { get; set; }
            public string col11 { get; set; }
            public string col12 { get; set; }
            public string col13 { get; set; }
            public string col14 { get; set; }
            public string col15 { get; set; }
            public string CompanyName { get; set; }
            public string CompanyID { get; set; }
            public string Outcome { get; set; }
            public Nullable<int> LimitationCount { get; set; }
            public string CaseNextHearing { get; set; }
            public string ClientName { get; set; }
            public string assignuserby { get; set; }
            public string assignuserto { get; set; }
            public string MasterCaseId { get; set; }
            public string Court_Status { get; set; }
            public string Disposeddate { get; set; }
            public string vAdvocatename { get; set; }
            public string PetitionerName { get; set; }
            public string RespondentName { get; set; }
            public string ULN { get; set; }
            public string NatureOfCase { get; set; }
            public string SebiMatterType { get; set; }
            public string MatterOf { get; set; }
            public string BriefOfMatter { get; set; }
            public string Relevance { get; set; }
            public string IssuesInvolved { get; set; }
            public string NatureOfViolation { get; set; }
            public string Casecategory { get; set; }
            public string DateOfImpugned { get; set; }
            public string IssuingAuthority { get; set; }
            public string DirectionUnderTheOrder { get; set; }
            public string ReplyField { get; set; }
            public string MatterStage { get; set; }
            public string StayOrder { get; set; }
            public string DateOfStayOrder { get; set; }
            public string NameOfParty { get; set; }
            public string DateTill { get; set; }
            public string ExtendedTill { get; set; }
            public string StayVacatedOn { get; set; }
            public string DirectionOfCourt { get; set; }
            public string ExpactedDateOfCompliance { get; set; }
            public string OprationDepartmentInchargeOFCompliance { get; set; }
            public string DateOfCompliance { get; set; }
            public string DisposalInFavour { get; set; }
            public string NatureOfDisposal { get; set; }
            public string OperationDepartmentForThePurposeOfSeeking { get; set; }
            public string NameOfTheDealingOfficer { get; set; }
            public string NameOfOfficer { get; set; }
            public string ProformaParty { get; set; }
            public string MarketActivity { get; set; }
            public string GovernmentAuthorityParty { get; set; }
            public string Remarks { get; set; }
            public string Name_State { get; set; }
            public string Name_City { get; set; }
            public string case_Nomenclature { get; set; }
            public string Filed_By_Against { get; set; }
            public string ActionStatus { get; set; }
            public string Solicitors { get; set; }
            public string CourtOrders { get; set; }
            public string Details_Of_Bench { get; set; }
            public string connectedmtr { get; set; }
            public string DeptTypefilter { get; set; }
    }
}