//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawPracticeFirm.ManuService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManuService.GetApiResultSoap")]
    public interface GetApiResultSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManupatraResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LawPracticeFirm.ManuService.GetManupatraResultResponse GetManupatraResult(LawPracticeFirm.ManuService.GetManupatraResultRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManupatraResult", ReplyAction="*")]
        System.Threading.Tasks.Task<LawPracticeFirm.ManuService.GetManupatraResultResponse> GetManupatraResultAsync(LawPracticeFirm.ManuService.GetManupatraResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManupatraResultLawPractice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LawPracticeFirm.ManuService.GetManupatraResultLawPracticeResponse GetManupatraResultLawPractice(LawPracticeFirm.ManuService.GetManupatraResultLawPracticeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManupatraResultLawPractice", ReplyAction="*")]
        System.Threading.Tasks.Task<LawPracticeFirm.ManuService.GetManupatraResultLawPracticeResponse> GetManupatraResultLawPracticeAsync(LawPracticeFirm.ManuService.GetManupatraResultLawPracticeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManupatraResulttest1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetManupatraResulttest1(string strkey, string strGUID, int inpage, string strtocvalue, string strField);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManupatraResulttest1", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetManupatraResulttest1Async(string strkey, string strGUID, int inpage, string strtocvalue, string strField);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManupatraResultForOffice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LawPracticeFirm.ManuService.GetManupatraResultForOfficeResponse GetManupatraResultForOffice(LawPracticeFirm.ManuService.GetManupatraResultForOfficeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManupatraResultForOffice", ReplyAction="*")]
        System.Threading.Tasks.Task<LawPracticeFirm.ManuService.GetManupatraResultForOfficeResponse> GetManupatraResultForOfficeAsync(LawPracticeFirm.ManuService.GetManupatraResultForOfficeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFederateResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetFederateResult(string q, string strGUID, int inpage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFederateResult", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetFederateResultAsync(string q, string strGUID, int inpage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManupatraResultTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetManupatraResultTest(string strkey, string strGUID, int inpage, string strtocvalue, int totcount, string strField);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManupatraResultTest", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetManupatraResultTestAsync(string strkey, string strGUID, int inpage, string strtocvalue, int totcount, string strField);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManuID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetManuID(string strkey, int inpage, string strcourt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManuID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetManuIDAsync(string strkey, int inpage, string strcourt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManuIDInSubject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetManuIDInSubject(string strkey, int inpage, string strcourt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManuIDInSubject", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetManuIDInSubjectAsync(string strkey, int inpage, string strcourt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLocation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetLocation(string strkey, int inpage, string strcourt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLocation", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetLocationAsync(string strkey, int inpage, string strcourt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Login(string strUserName, string strPassword, string strSessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LoginAsync(string strUserName, string strPassword, string strSessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginOA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LoginOA(string strUserName, string strPassword, string strSessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginOA", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LoginOAAsync(string strUserName, string strPassword, string strSessionId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/LogOut")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void LogOut(string strUserName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/LogOut")]
        System.Threading.Tasks.Task LogOutAsync(string strUserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCourtList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCourtList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCourtList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCourtListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewDoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ViewDoc(string strUserGuid, string strParam, string strPath, string strCollection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewDoc", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ViewDocAsync(string strUserGuid, string strParam, string strPath, string strCollection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EncryptBase64", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EncryptBase64(string normalText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EncryptBase64", ReplyAction="*")]
        System.Threading.Tasks.Task<string> EncryptBase64Async(string normalText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DecryptBase64", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DecryptBase64(string encriptedText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DecryptBase64", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DecryptBase64Async(string encriptedText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetToken(string strUserGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetToken", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetTokenAsync(string strUserGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTitle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetTitle(string strmanuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTitle", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetTitleAsync(string strmanuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getactlink", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Getactlink(string stract, string strsec, int sectiontype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getactlink", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetactlinkAsync(string stract, string strsec, int sectiontype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAllAct(string act, string strmodule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAct", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetAllActAsync(string act, string strmodule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMobileLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMobileLogin(string stUserId, string stPasswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMobileLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetMobileLoginAsync(string stUserId, string stPasswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login_Mobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Login_Mobile(string stUserId, string stPasswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login_Mobile", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Login_MobileAsync(string stUserId, string stPasswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowActDesc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ShowActDesc(string stCompID, string stGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowActDesc", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ShowActDescAsync(string stCompID, string stGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowActDescOfficeApi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ShowActDescOfficeApi(string stCompID, string stGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowActDescOfficeApi", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ShowActDescOfficeApiAsync(string stCompID, string stGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowCompTitle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LawPracticeFirm.ManuService.BaCompTitle ShowCompTitle(string stCompID, string stGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowCompTitle", ReplyAction="*")]
        System.Threading.Tasks.Task<LawPracticeFirm.ManuService.BaCompTitle> ShowCompTitleAsync(string stCompID, string stGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManuIdByTitle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetManuIdByTitle(string strtitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManuIdByTitle", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetManuIdByTitleAsync(string strtitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPieChartData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPieChartData(string stManuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPieChartData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPieChartDataAsync(string stManuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCaseCited", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCaseCited(string strManuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCaseCited", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCaseCitedAsync(string strManuid);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetManupatraResult", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetManupatraResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strkey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strGUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int inpage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strtocvalue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int totcount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string strField;
        
        public GetManupatraResultRequest() {
        }
        
        public GetManupatraResultRequest(string strkey, string strGUID, int inpage, string strtocvalue, int totcount, string strField) {
            this.strkey = strkey;
            this.strGUID = strGUID;
            this.inpage = inpage;
            this.strtocvalue = strtocvalue;
            this.totcount = totcount;
            this.strField = strField;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetManupatraResultResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetManupatraResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable GetManupatraResultResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int totcount;
        
        public GetManupatraResultResponse() {
        }
        
        public GetManupatraResultResponse(System.Data.DataTable GetManupatraResultResult, int totcount) {
            this.GetManupatraResultResult = GetManupatraResultResult;
            this.totcount = totcount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetManupatraResultLawPractice", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetManupatraResultLawPracticeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strkey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strGUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int inpage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strtocvalue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int totcount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string strField;
        
        public GetManupatraResultLawPracticeRequest() {
        }
        
        public GetManupatraResultLawPracticeRequest(string strkey, string strGUID, int inpage, string strtocvalue, int totcount, string strField) {
            this.strkey = strkey;
            this.strGUID = strGUID;
            this.inpage = inpage;
            this.strtocvalue = strtocvalue;
            this.totcount = totcount;
            this.strField = strField;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetManupatraResultLawPracticeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetManupatraResultLawPracticeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable GetManupatraResultLawPracticeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int totcount;
        
        public GetManupatraResultLawPracticeResponse() {
        }
        
        public GetManupatraResultLawPracticeResponse(System.Data.DataTable GetManupatraResultLawPracticeResult, int totcount) {
            this.GetManupatraResultLawPracticeResult = GetManupatraResultLawPracticeResult;
            this.totcount = totcount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetManupatraResultForOffice", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetManupatraResultForOfficeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strkey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strGUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int inpage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strtocvalue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int totcount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string QDF;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string strField;
        
        public GetManupatraResultForOfficeRequest() {
        }
        
        public GetManupatraResultForOfficeRequest(string strkey, string strGUID, int inpage, string strtocvalue, int totcount, string QDF, string strField) {
            this.strkey = strkey;
            this.strGUID = strGUID;
            this.inpage = inpage;
            this.strtocvalue = strtocvalue;
            this.totcount = totcount;
            this.QDF = QDF;
            this.strField = strField;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetManupatraResultForOfficeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetManupatraResultForOfficeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable GetManupatraResultForOfficeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int totcount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string QDF;
        
        public GetManupatraResultForOfficeResponse() {
        }
        
        public GetManupatraResultForOfficeResponse(System.Data.DataTable GetManupatraResultForOfficeResult, int totcount, string QDF) {
            this.GetManupatraResultForOfficeResult = GetManupatraResultForOfficeResult;
            this.totcount = totcount;
            this.QDF = QDF;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaCompTitle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string compDescField;
        
        private string compValField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CompDesc {
            get {
                return this.compDescField;
            }
            set {
                this.compDescField = value;
                this.RaisePropertyChanged("CompDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CompVal {
            get {
                return this.compValField;
            }
            set {
                this.compValField = value;
                this.RaisePropertyChanged("CompVal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetApiResultSoapChannel : LawPracticeFirm.ManuService.GetApiResultSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetApiResultSoapClient : System.ServiceModel.ClientBase<LawPracticeFirm.ManuService.GetApiResultSoap>, LawPracticeFirm.ManuService.GetApiResultSoap {
        
        public GetApiResultSoapClient() {
        }
        
        public GetApiResultSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetApiResultSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetApiResultSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetApiResultSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LawPracticeFirm.ManuService.GetManupatraResultResponse LawPracticeFirm.ManuService.GetApiResultSoap.GetManupatraResult(LawPracticeFirm.ManuService.GetManupatraResultRequest request) {
            return base.Channel.GetManupatraResult(request);
        }
        
        public System.Data.DataTable GetManupatraResult(string strkey, string strGUID, int inpage, string strtocvalue, ref int totcount, string strField) {
            LawPracticeFirm.ManuService.GetManupatraResultRequest inValue = new LawPracticeFirm.ManuService.GetManupatraResultRequest();
            inValue.strkey = strkey;
            inValue.strGUID = strGUID;
            inValue.inpage = inpage;
            inValue.strtocvalue = strtocvalue;
            inValue.totcount = totcount;
            inValue.strField = strField;
            LawPracticeFirm.ManuService.GetManupatraResultResponse retVal = ((LawPracticeFirm.ManuService.GetApiResultSoap)(this)).GetManupatraResult(inValue);
            totcount = retVal.totcount;
            return retVal.GetManupatraResultResult;
        }
        
        public System.Threading.Tasks.Task<LawPracticeFirm.ManuService.GetManupatraResultResponse> GetManupatraResultAsync(LawPracticeFirm.ManuService.GetManupatraResultRequest request) {
            return base.Channel.GetManupatraResultAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LawPracticeFirm.ManuService.GetManupatraResultLawPracticeResponse LawPracticeFirm.ManuService.GetApiResultSoap.GetManupatraResultLawPractice(LawPracticeFirm.ManuService.GetManupatraResultLawPracticeRequest request) {
            return base.Channel.GetManupatraResultLawPractice(request);
        }
        
        public System.Data.DataTable GetManupatraResultLawPractice(string strkey, string strGUID, int inpage, string strtocvalue, ref int totcount, string strField) {
            LawPracticeFirm.ManuService.GetManupatraResultLawPracticeRequest inValue = new LawPracticeFirm.ManuService.GetManupatraResultLawPracticeRequest();
            inValue.strkey = strkey;
            inValue.strGUID = strGUID;
            inValue.inpage = inpage;
            inValue.strtocvalue = strtocvalue;
            inValue.totcount = totcount;
            inValue.strField = strField;
            LawPracticeFirm.ManuService.GetManupatraResultLawPracticeResponse retVal = ((LawPracticeFirm.ManuService.GetApiResultSoap)(this)).GetManupatraResultLawPractice(inValue);
            totcount = retVal.totcount;
            return retVal.GetManupatraResultLawPracticeResult;
        }
        
        public System.Threading.Tasks.Task<LawPracticeFirm.ManuService.GetManupatraResultLawPracticeResponse> GetManupatraResultLawPracticeAsync(LawPracticeFirm.ManuService.GetManupatraResultLawPracticeRequest request) {
            return base.Channel.GetManupatraResultLawPracticeAsync(request);
        }
        
        public string GetManupatraResulttest1(string strkey, string strGUID, int inpage, string strtocvalue, string strField) {
            return base.Channel.GetManupatraResulttest1(strkey, strGUID, inpage, strtocvalue, strField);
        }
        
        public System.Threading.Tasks.Task<string> GetManupatraResulttest1Async(string strkey, string strGUID, int inpage, string strtocvalue, string strField) {
            return base.Channel.GetManupatraResulttest1Async(strkey, strGUID, inpage, strtocvalue, strField);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LawPracticeFirm.ManuService.GetManupatraResultForOfficeResponse LawPracticeFirm.ManuService.GetApiResultSoap.GetManupatraResultForOffice(LawPracticeFirm.ManuService.GetManupatraResultForOfficeRequest request) {
            return base.Channel.GetManupatraResultForOffice(request);
        }
        
        public System.Data.DataTable GetManupatraResultForOffice(string strkey, string strGUID, int inpage, string strtocvalue, ref int totcount, ref string QDF, string strField) {
            LawPracticeFirm.ManuService.GetManupatraResultForOfficeRequest inValue = new LawPracticeFirm.ManuService.GetManupatraResultForOfficeRequest();
            inValue.strkey = strkey;
            inValue.strGUID = strGUID;
            inValue.inpage = inpage;
            inValue.strtocvalue = strtocvalue;
            inValue.totcount = totcount;
            inValue.QDF = QDF;
            inValue.strField = strField;
            LawPracticeFirm.ManuService.GetManupatraResultForOfficeResponse retVal = ((LawPracticeFirm.ManuService.GetApiResultSoap)(this)).GetManupatraResultForOffice(inValue);
            totcount = retVal.totcount;
            QDF = retVal.QDF;
            return retVal.GetManupatraResultForOfficeResult;
        }
        
        public System.Threading.Tasks.Task<LawPracticeFirm.ManuService.GetManupatraResultForOfficeResponse> GetManupatraResultForOfficeAsync(LawPracticeFirm.ManuService.GetManupatraResultForOfficeRequest request) {
            return base.Channel.GetManupatraResultForOfficeAsync(request);
        }
        
        public System.Data.DataTable GetFederateResult(string q, string strGUID, int inpage) {
            return base.Channel.GetFederateResult(q, strGUID, inpage);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetFederateResultAsync(string q, string strGUID, int inpage) {
            return base.Channel.GetFederateResultAsync(q, strGUID, inpage);
        }
        
        public System.Data.DataTable GetManupatraResultTest(string strkey, string strGUID, int inpage, string strtocvalue, int totcount, string strField) {
            return base.Channel.GetManupatraResultTest(strkey, strGUID, inpage, strtocvalue, totcount, strField);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetManupatraResultTestAsync(string strkey, string strGUID, int inpage, string strtocvalue, int totcount, string strField) {
            return base.Channel.GetManupatraResultTestAsync(strkey, strGUID, inpage, strtocvalue, totcount, strField);
        }
        
        public string GetManuID(string strkey, int inpage, string strcourt) {
            return base.Channel.GetManuID(strkey, inpage, strcourt);
        }
        
        public System.Threading.Tasks.Task<string> GetManuIDAsync(string strkey, int inpage, string strcourt) {
            return base.Channel.GetManuIDAsync(strkey, inpage, strcourt);
        }
        
        public string GetManuIDInSubject(string strkey, int inpage, string strcourt) {
            return base.Channel.GetManuIDInSubject(strkey, inpage, strcourt);
        }
        
        public System.Threading.Tasks.Task<string> GetManuIDInSubjectAsync(string strkey, int inpage, string strcourt) {
            return base.Channel.GetManuIDInSubjectAsync(strkey, inpage, strcourt);
        }
        
        public string GetLocation(string strkey, int inpage, string strcourt) {
            return base.Channel.GetLocation(strkey, inpage, strcourt);
        }
        
        public System.Threading.Tasks.Task<string> GetLocationAsync(string strkey, int inpage, string strcourt) {
            return base.Channel.GetLocationAsync(strkey, inpage, strcourt);
        }
        
        public string Login(string strUserName, string strPassword, string strSessionId) {
            return base.Channel.Login(strUserName, strPassword, strSessionId);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string strUserName, string strPassword, string strSessionId) {
            return base.Channel.LoginAsync(strUserName, strPassword, strSessionId);
        }
        
        public string LoginOA(string strUserName, string strPassword, string strSessionId) {
            return base.Channel.LoginOA(strUserName, strPassword, strSessionId);
        }
        
        public System.Threading.Tasks.Task<string> LoginOAAsync(string strUserName, string strPassword, string strSessionId) {
            return base.Channel.LoginOAAsync(strUserName, strPassword, strSessionId);
        }
        
        public void LogOut(string strUserName) {
            base.Channel.LogOut(strUserName);
        }
        
        public System.Threading.Tasks.Task LogOutAsync(string strUserName) {
            return base.Channel.LogOutAsync(strUserName);
        }
        
        public System.Data.DataTable GetCourtList() {
            return base.Channel.GetCourtList();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCourtListAsync() {
            return base.Channel.GetCourtListAsync();
        }
        
        public string ViewDoc(string strUserGuid, string strParam, string strPath, string strCollection) {
            return base.Channel.ViewDoc(strUserGuid, strParam, strPath, strCollection);
        }
        
        public System.Threading.Tasks.Task<string> ViewDocAsync(string strUserGuid, string strParam, string strPath, string strCollection) {
            return base.Channel.ViewDocAsync(strUserGuid, strParam, strPath, strCollection);
        }
        
        public string EncryptBase64(string normalText) {
            return base.Channel.EncryptBase64(normalText);
        }
        
        public System.Threading.Tasks.Task<string> EncryptBase64Async(string normalText) {
            return base.Channel.EncryptBase64Async(normalText);
        }
        
        public string DecryptBase64(string encriptedText) {
            return base.Channel.DecryptBase64(encriptedText);
        }
        
        public System.Threading.Tasks.Task<string> DecryptBase64Async(string encriptedText) {
            return base.Channel.DecryptBase64Async(encriptedText);
        }
        
        public string GetToken(string strUserGuid) {
            return base.Channel.GetToken(strUserGuid);
        }
        
        public System.Threading.Tasks.Task<string> GetTokenAsync(string strUserGuid) {
            return base.Channel.GetTokenAsync(strUserGuid);
        }
        
        public string GetTitle(string strmanuid) {
            return base.Channel.GetTitle(strmanuid);
        }
        
        public System.Threading.Tasks.Task<string> GetTitleAsync(string strmanuid) {
            return base.Channel.GetTitleAsync(strmanuid);
        }
        
        public string Getactlink(string stract, string strsec, int sectiontype) {
            return base.Channel.Getactlink(stract, strsec, sectiontype);
        }
        
        public System.Threading.Tasks.Task<string> GetactlinkAsync(string stract, string strsec, int sectiontype) {
            return base.Channel.GetactlinkAsync(stract, strsec, sectiontype);
        }
        
        public string GetAllAct(string act, string strmodule) {
            return base.Channel.GetAllAct(act, strmodule);
        }
        
        public System.Threading.Tasks.Task<string> GetAllActAsync(string act, string strmodule) {
            return base.Channel.GetAllActAsync(act, strmodule);
        }
        
        public string GetMobileLogin(string stUserId, string stPasswd) {
            return base.Channel.GetMobileLogin(stUserId, stPasswd);
        }
        
        public System.Threading.Tasks.Task<string> GetMobileLoginAsync(string stUserId, string stPasswd) {
            return base.Channel.GetMobileLoginAsync(stUserId, stPasswd);
        }
        
        public string Login_Mobile(string stUserId, string stPasswd) {
            return base.Channel.Login_Mobile(stUserId, stPasswd);
        }
        
        public System.Threading.Tasks.Task<string> Login_MobileAsync(string stUserId, string stPasswd) {
            return base.Channel.Login_MobileAsync(stUserId, stPasswd);
        }
        
        public string ShowActDesc(string stCompID, string stGuid) {
            return base.Channel.ShowActDesc(stCompID, stGuid);
        }
        
        public System.Threading.Tasks.Task<string> ShowActDescAsync(string stCompID, string stGuid) {
            return base.Channel.ShowActDescAsync(stCompID, stGuid);
        }
        
        public string ShowActDescOfficeApi(string stCompID, string stGuid) {
            return base.Channel.ShowActDescOfficeApi(stCompID, stGuid);
        }
        
        public System.Threading.Tasks.Task<string> ShowActDescOfficeApiAsync(string stCompID, string stGuid) {
            return base.Channel.ShowActDescOfficeApiAsync(stCompID, stGuid);
        }
        
        public LawPracticeFirm.ManuService.BaCompTitle ShowCompTitle(string stCompID, string stGuid) {
            return base.Channel.ShowCompTitle(stCompID, stGuid);
        }
        
        public System.Threading.Tasks.Task<LawPracticeFirm.ManuService.BaCompTitle> ShowCompTitleAsync(string stCompID, string stGuid) {
            return base.Channel.ShowCompTitleAsync(stCompID, stGuid);
        }
        
        public string GetManuIdByTitle(string strtitle) {
            return base.Channel.GetManuIdByTitle(strtitle);
        }
        
        public System.Threading.Tasks.Task<string> GetManuIdByTitleAsync(string strtitle) {
            return base.Channel.GetManuIdByTitleAsync(strtitle);
        }
        
        public System.Data.DataSet GetPieChartData(string stManuid) {
            return base.Channel.GetPieChartData(stManuid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPieChartDataAsync(string stManuid) {
            return base.Channel.GetPieChartDataAsync(stManuid);
        }
        
        public System.Data.DataSet GetCaseCited(string strManuid) {
            return base.Channel.GetCaseCited(strManuid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCaseCitedAsync(string strManuid) {
            return base.Channel.GetCaseCitedAsync(strManuid);
        }
    }
}
