//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddContactsList
    {
        public System.Guid cid { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string homeno { get; set; }
        public string mobno { get; set; }
        public string offno { get; set; }
        public string fax { get; set; }
        public string cemail { get; set; }
        public Nullable<int> cport { get; set; }
        public string cnotes { get; set; }
        public string cadd1 { get; set; }
        public string cassign { get; set; }
        public string ctags { get; set; }
        public string cnumber { get; set; }
        public string cwebsite { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string cphoto { get; set; }
        public string mname { get; set; }
        public string col1 { get; set; }
        public string col2 { get; set; }
        public string col3 { get; set; }
        public string col4 { get; set; }
        public string col5 { get; set; }
        public string col6 { get; set; }
        public string col7 { get; set; }
        public string col8 { get; set; }
        public string col9 { get; set; }
        public string col10 { get; set; }
        public string col11 { get; set; }
        public string col12 { get; set; }
        public string col13 { get; set; }
        public string col14 { get; set; }
        public string col15 { get; set; }
        public Nullable<System.Guid> firmuser { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
        public string ContactType { get; set; }
        public Nullable<int> IsSync { get; set; }
        public string ProfileType { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string PropectType { get; set; }
        public string SourceRef { get; set; }
        public string Designation { get; set; }
        public string casetype { get; set; }
        public string CompanyId { get; set; }
        public string City { get; set; }
        public string Pin { get; set; }
        public string GSTINNo { get; set; }
        public string PANNo { get; set; }
        public string AadharCardNo { get; set; }
        public string CompanyStructure { get; set; }
        public Nullable<int> IsCompany { get; set; }
        public Nullable<int> IsCompanyAdmin { get; set; }
        public string VendorRefID { get; set; }
    }
}
