//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddRemindList
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> formid { get; set; }
        public Nullable<System.Guid> rpid { get; set; }
        public string rtype { get; set; }
        public string rnum { get; set; }
        public string rtime { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
    }
}
