//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllTablesCol
    {
        public int id { get; set; }
        public string TableName { get; set; }
        public string TableCols { get; set; }
        public string Active { get; set; }
    }
}
