//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditError
    {
        public System.Guid ID { get; set; }
        public Nullable<int> EventTypeId { get; set; }
        public Nullable<int> SeverityId { get; set; }
        public Nullable<int> RequestTypeId { get; set; }
        public string Sevirity { get; set; }
        public string RequestType { get; set; }
        public string EventType { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> EventTime { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
        public Nullable<byte> LogType { get; set; }
        public string Remark { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
    }
}
