//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomField
    {
        public long Id { get; set; }
        public string Text { get; set; }
        public string DefaultValues { get; set; }
        public string Formatter { get; set; }
        public string Url { get; set; }
        public bool IsActive { get; set; }
        public bool AvailableInWorkflow { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
    }
}
