//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeleteDataCollection
    {
        public System.Guid Iid { get; set; }
        public Nullable<System.Guid> rowid { get; set; }
        public string tablename { get; set; }
        public Nullable<System.Guid> firmid { get; set; }
        public Nullable<System.Guid> userid { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
    }
}
