//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmUserPermission
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public Nullable<long> CaseId { get; set; }
        public string Module { get; set; }
        public string AccessRight { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
        public System.Guid firmid { get; set; }
    }
}
