//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmTask
    {
        public long Id { get; set; }
        public string FirmId { get; set; }
        public string UserId { get; set; }
        public long ParentTaskId { get; set; }
        public string DependentTaskIds { get; set; }
        public string DependantOnTaskIds { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
    }
}
