//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firm
    {
        public System.Guid Id { get; set; }
        public string FirmCode { get; set; }
        public string FirmTitle { get; set; }
        public string FirmName { get; set; }
        public Nullable<long> AdminUser { get; set; }
        public string FirmDetails { get; set; }
        public string FirmAddress1 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string FirmContactno { get; set; }
        public string FirmContactEmail { get; set; }
        public bool IsActive { get; set; }
        public string Country { get; set; }
        public string PinCode { get; set; }
        public Nullable<System.DateTime> SubscriptionStartDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> GracePeriod { get; set; }
        public string Module { get; set; }
        public Nullable<byte> iTrail { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string FirmAddress2 { get; set; }
        public string FirmBriefDetails { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
        public string Landline { get; set; }
        public string SecondEmail { get; set; }
        public Nullable<int> SyncType { get; set; }
        public Nullable<int> SyncStatus { get; set; }
        public Nullable<int> PackModule { get; set; }
        public Nullable<long> DocumentSize { get; set; }
        public Nullable<byte> itype { get; set; }
        public Nullable<byte> Itrial { get; set; }
        public string secondaryname { get; set; }
        public string secondarymobile { get; set; }
    }
}
