//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmWorkFlowAttachItemDetail
    {
        public long Id { get; set; }
        public long WorkFlowAttachItemId { get; set; }
        public long ObjectId { get; set; }
        public string PreviousObjectIds { get; set; }
        public string NextObjctIds { get; set; }
        public string OutPutObjectIds { get; set; }
        public Nullable<long> FormId { get; set; }
        public string AssignTo { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string ObjectType { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
    }
}
