//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmCustomForm
    {
        public System.Guid Id { get; set; }
        public string FormName { get; set; }
        public bool IsActive { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<bool> IsArchieved { get; set; }
        public Nullable<System.Guid> userid { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
    }
}
