//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    
    public partial class GetEventDetails_Result1
    {
        public long Id { get; set; }
        public Nullable<long> firmid { get; set; }
        public string tcontact { get; set; }
        public string tmatter { get; set; }
        public string tsubject { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<System.TimeSpan> stime { get; set; }
        public Nullable<System.TimeSpan> etime { get; set; }
        public Nullable<int> eallday { get; set; }
        public string ecolor { get; set; }
        public string elocation { get; set; }
        public string tdetails { get; set; }
        public string tpriority { get; set; }
        public string trepeat { get; set; }
        public string tauser { get; set; }
        public string tacontact { get; set; }
        public string ttags { get; set; }
        public string tfile { get; set; }
        public Nullable<int> teassign { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string fname { get; set; }
        public string mname { get; set; }
        public string lname { get; set; }
        public string mattername { get; set; }
    }
}
