//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    
    public partial class GetMattersDetail_Result2
    {
        public string Id { get; set; }
        public Nullable<System.Guid> firmId { get; set; }
        public Nullable<System.Guid> cid { get; set; }
        public string mnotes { get; set; }
        public Nullable<System.DateTime> msol { get; set; }
        public Nullable<System.DateTime> odate { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public Nullable<System.Guid> assignto { get; set; }
        public string orgaty { get; set; }
        public string tags { get; set; }
        public string cstatus { get; set; }
        public string mtrno { get; set; }
        public string col1 { get; set; }
        public string col2 { get; set; }
        public string col3 { get; set; }
        public string col4 { get; set; }
        public string col5 { get; set; }
        public string col6 { get; set; }
        public string col7 { get; set; }
        public string col8 { get; set; }
        public string col9 { get; set; }
        public string col10 { get; set; }
        public string col11 { get; set; }
        public string col12 { get; set; }
        public string col13 { get; set; }
        public string col14 { get; set; }
        public string col15 { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string mname { get; set; }
        public string fname { get; set; }
        public string mdname { get; set; }
        public string lname { get; set; }
        public Nullable<System.Guid> firmuser { get; set; }
        public string cnrno { get; set; }
        public Nullable<System.Guid> assignid { get; set; }
        public string assignuser { get; set; }
        public string UserCaseid { get; set; }
        public Nullable<System.Guid> matterclientid { get; set; }
        public string UserName { get; set; }
        public string assignuserby { get; set; }
        public string assignuserto { get; set; }
        public string cfile { get; set; }
        public string TotalCaseTime { get; set; }
        public string CaseSubject { get; set; }
    }
}
