//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPool
    {
        public decimal ids { get; set; }
        public string vUserName { get; set; }
        public string vIPAdd { get; set; }
        public Nullable<System.DateTime> dCrDate { get; set; }
        public string iptype { get; set; }
        public Nullable<int> iNumLog { get; set; }
        public Nullable<int> iAllowProfile { get; set; }
        public Nullable<int> iAllowDirectLogin { get; set; }
        public Nullable<int> iPage { get; set; }
        public string vLogo { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
    }
}
