//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleFieldInformation
    {
        public long Id { get; set; }
        public long FirmId { get; set; }
        public int Sequence { get; set; }
        public long ConfigurationType { get; set; }
        public long FieldType { get; set; }
        public string FieldName { get; set; }
        public bool IsRequired { get; set; }
        public int MinLength { get; set; }
        public int MaxLength { get; set; }
        public bool IsDefault { get; set; }
        public bool IsPositionChangable { get; set; }
        public string SubConfigurationType { get; set; }
        public string DefaultValues { get; set; }
        public string Formatter { get; set; }
        public string Url { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
    }
}
