//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegClient
    {
        public long Id { get; set; }
        public string cfname { get; set; }
        public string cemail { get; set; }
        public string cmobile { get; set; }
        public string clandline { get; set; }
        public string caddress { get; set; }
        public string country { get; set; }
        public string cstate { get; set; }
        public string ccity { get; set; }
        public string cphoto { get; set; }
        public Nullable<long> LoginId { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<long> firmuser { get; set; }
        public Nullable<long> leadid { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
        public Nullable<long> Firmid { get; set; }
    }
}
