//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaveCustomActivityData
    {
        public System.Guid cid { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
        public Nullable<System.Guid> formId { get; set; }
        public Nullable<System.Guid> Userid { get; set; }
        public Nullable<System.Guid> caseid { get; set; }
        public string subject { get; set; }
        public Nullable<System.Guid> assignto { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string col1 { get; set; }
        public string col2 { get; set; }
        public string col3 { get; set; }
        public string col4 { get; set; }
        public string col5 { get; set; }
        public string col6 { get; set; }
        public string col7 { get; set; }
        public string col8 { get; set; }
        public string col9 { get; set; }
        public string col10 { get; set; }
        public string col11 { get; set; }
        public string col12 { get; set; }
        public string col13 { get; set; }
        public string col14 { get; set; }
        public string col15 { get; set; }
        public Nullable<long> Status { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
        public Nullable<int> IsSync { get; set; }
    }
}
