//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AssignCaseAlertUser
    {
        public System.Guid AId { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
        public Nullable<System.Guid> AlertId { get; set; }
        public Nullable<System.Guid> AssignUser { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
    }
}
