//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ActivityAlertSetting
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
        public Nullable<System.Guid> Userid { get; set; }
        public Nullable<System.Guid> EventId { get; set; }
        public string EventName { get; set; }
        public Nullable<int> Alert { get; set; }
        public Nullable<int> alertDays { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> Date_time { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
        public Nullable<System.DateTime> AlertDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> IsSent { get; set; }
        public string CreatedForReminder { get; set; }
    }
}
