//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TimeEntry
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> tmatter { get; set; }
        public string subject { get; set; }
        public Nullable<System.DateTime> tdate { get; set; }
        public string callDura { get; set; }
        public string tdetails { get; set; }
        public string tprivnotes { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
        public Nullable<System.Guid> userid { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
        public Nullable<int> IsSync { get; set; }
    }
}
