//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RightsPageData
    {
        public long Id { get; set; }
        public string RoleType { get; set; }
        public string PageName { get; set; }
        public string Pagelink { get; set; }
        public string PageGroup { get; set; }
        public string date_time { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> isnested { get; set; }
        public Nullable<int> ParentPage { get; set; }
        public Nullable<int> Write { get; set; }
        public Nullable<int> View { get; set; }
        public Nullable<int> Edit { get; set; }
        public Nullable<int> Delete { get; set; }
        public Nullable<int> ViewAll { get; set; }
        public Nullable<int> EditAll { get; set; }
        public Nullable<int> IsParent { get; set; }
    }
}
