//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAnotherAddressInvoice
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
        public Nullable<System.Guid> userid { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string Phoneno { get; set; }
        public string Email { get; set; }
        public string website { get; set; }
        public string GSTNo { get; set; }
        public string Pan { get; set; }
        public string Sac { get; set; }
        public Nullable<int> Isactive { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
        public Nullable<int> isdefault { get; set; }
    }
}
