//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHome
    {
        public System.Guid Id { get; set; }
        public string LogoPath { get; set; }
        public string LogoHeading { get; set; }
        public string Logotext { get; set; }
        public string Aboutus { get; set; }
        public string Services { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string BackgroundImg { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
        public string LogoPosition { get; set; }
        public Nullable<int> IsNotice { get; set; }
    }
}
