//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblImportToCaseData
    {
        public long Id { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string Tags { get; set; }
        public string CaseStatus { get; set; }
        public string CaseNumber { get; set; }
        public string CaseName { get; set; }
        public string CNRNumber { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<System.Guid> firmuser { get; set; }
        public Nullable<System.Guid> AssignTo { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
    }
}
