//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblImportToLeadData
    {
        public long lid { get; set; }
        public string ProspectName { get; set; }
        public string ContactPerson { get; set; }
        public string Organization { get; set; }
        public string Designation { get; set; }
        public string Address { get; set; }
        public string Pin { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
        public Nullable<System.Guid> firmuser { get; set; }
    }
}
