//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblInvoiceEntry
    {
        public System.Guid Iid { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.Guid> InvoiceId { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
        public Nullable<System.Guid> userid { get; set; }
        public string type { get; set; }
        public string itemname { get; set; }
        public Nullable<System.Guid> caseid { get; set; }
        public Nullable<System.Guid> billyby { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> QtyORHour { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
        public Nullable<int> isinvoicetax { get; set; }
    
        public virtual TblInvoice TblInvoice { get; set; }
    }
}
