//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblInvoice()
        {
            this.TblInvoiceEntries = new HashSet<TblInvoiceEntry>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
        public Nullable<System.Guid> userid { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.Guid> clientid { get; set; }
        public string state { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> invdate { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public string mobile { get; set; }
        public string paystatus { get; set; }
        public string IGSTPer { get; set; }
        public string CGSTPer { get; set; }
        public string SGSTPer { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> IGST { get; set; }
        public Nullable<double> CGST { get; set; }
        public Nullable<double> SGST { get; set; }
        public Nullable<double> TotAmt { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Inovicedate { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
        public Nullable<System.Guid> BillerAddress { get; set; }
        public Nullable<System.Guid> addressid { get; set; }
        public string shipstate { get; set; }
        public string shipaddress { get; set; }
        public Nullable<int> PaymentReceived { get; set; }
        public Nullable<int> isinvoicetax { get; set; }
        public string UserNameInvoice { get; set; }
        public string InvoiceEmail { get; set; }
        public string matterid { get; set; }
        public Nullable<int> IsInvoiceClientShared { get; set; }
        public Nullable<int> IsAmend { get; set; }
        public string OriginalInvoiceNo { get; set; }
        public Nullable<int> IsCanceled { get; set; }
        public string ClientGSTNo { get; set; }
        public string ClientPanNo { get; set; }
        public string ISubject { get; set; }
        public string IReference { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblInvoiceEntry> TblInvoiceEntries { get; set; }
    }
}
