//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblImportToContactData
    {
        public long cid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string HomeNo { get; set; }
        public string MobileNo { get; set; }
        public string OfficeNo { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Notes { get; set; }
        public string Address { get; set; }
        public string Tags { get; set; }
        public string Website { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<System.Guid> firmuser { get; set; }
        public Nullable<System.Guid> Assignto { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
    }
}
