//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManuCaseWiseType
    {
        public decimal iid { get; set; }
        public string vCaseType { get; set; }
        public string vCaseTypeName { get; set; }
        public string vCourt { get; set; }
        public string vBench { get; set; }
        public string vSide { get; set; }
        public string vCourtTitle { get; set; }
        public string vBenchName { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
    }
}
