//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotice
    {
        public System.Guid NoticeId { get; set; }
        public string FirmId { get; set; }
        public string UserId { get; set; }
        public string CaseStatus { get; set; }
        public string NoticeType { get; set; }
        public string AssignmentofTask { get; set; }
        public Nullable<System.DateTime> GenerationofAlerts { get; set; }
        public Nullable<System.DateTime> NoticeCreatedOn { get; set; }
        public Nullable<System.DateTime> DateofNotice { get; set; }
        public string ModeofServiceorDelivery { get; set; }
        public string AddressedTo { get; set; }
        public string AddresseeAddress { get; set; }
        public string OtherDetailsofAddressee { get; set; }
        public string SendersName { get; set; }
        public string SendersAddress { get; set; }
        public string OtherDetailsofSender { get; set; }
        public string NoticeSubject { get; set; }
        public string NoticeTitle { get; set; }
        public string CreateNotice { get; set; }
        public string NoticeThrough { get; set; }
        public Nullable<System.DateTime> DateofDelivery { get; set; }
        public Nullable<System.DateTime> DateofReceipt { get; set; }
        public string CurrentStatus { get; set; }
        public string NoticeReceivedbyClient { get; set; }
        public string NoticeBroughtbyClientforReply { get; set; }
        public Nullable<System.DateTime> ReplytoNoticeCreatedOn { get; set; }
        public Nullable<System.DateTime> DateofReply { get; set; }
        public string ReplyAddressedto { get; set; }
        public string RespondentsName { get; set; }
        public string RespondentsAddress { get; set; }
        public string OtherDetailsofRespondent { get; set; }
        public string NoticeReference { get; set; }
        public string ReplySubject { get; set; }
        public string CreateReply { get; set; }
        public string Rejoinder { get; set; }
        public string ReplyThrough { get; set; }
        public Nullable<System.DateTime> DateofDispatchofNotice { get; set; }
        public Nullable<System.DateTime> DateofServiceofNotice { get; set; }
        public Nullable<System.DateTime> DateofReplytoNotice { get; set; }
        public Nullable<System.DateTime> DateofReceivingReply { get; set; }
        public string ModeofReceipt { get; set; }
        public string ModeofDeliveryofRejoinder { get; set; }
        public Nullable<System.DateTime> DateofCreatingRejoinder { get; set; }
        public Nullable<System.DateTime> DateofRejoinder { get; set; }
        public string RejoinderAddressedto { get; set; }
        public string NoticeandReplyReference { get; set; }
        public string RejoinderSubject { get; set; }
        public string CreateRejoinder { get; set; }
        public string RejoinderThrough { get; set; }
        public string TypeofNotice { get; set; }
        public string ApprovedForDispatch { get; set; }
        public Nullable<bool> ApproveByManager { get; set; }
        public Nullable<bool> ApproveByClient { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string MainNoticeId { get; set; }
        public string SentToClientId { get; set; }
        public string SentToManagerId { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public string Criticality { get; set; }
        public Nullable<System.DateTime> ActualDateOfClosure { get; set; }
        public string AmountClaimed { get; set; }
        public string SonOf { get; set; }
        public string RoOf { get; set; }
        public string Tag { get; set; }
        public string AlertBeforeDay { get; set; }
        public Nullable<System.DateTime> NotifiyDate { get; set; }
        public string Resonforhighpriority { get; set; }
        public string NoticeInitiatedBy { get; set; }
        public string ParentNoticeId { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
        public string NoticeThroughId { get; set; }
        public Nullable<System.DateTime> NoticeSentToClientDate { get; set; }
        public string TrackingId { get; set; }
        public string RootNoticeId { get; set; }
        public Nullable<System.DateTime> DueDateOfNotice { get; set; }
        public string Senderothertxt { get; set; }
        public string SenderNameId { get; set; }
        public string IsdeleteNotice { get; set; }
        public string SubectId { get; set; }
        public string SentThrough { get; set; }
        public string IntNoticeReference { get; set; }
        public Nullable<System.DateTime> CustomDueDateAlert { get; set; }
        public string AlertRemark { get; set; }
    }
}
