//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRejoinderNotice
    {
        public string CaseStatus { get; set; }
        public string NoticeType { get; set; }
        public string StatutoryProvision { get; set; }
        public Nullable<System.DateTime> DateofNotice { get; set; }
        public Nullable<System.DateTime> DateofDispatchofNotice { get; set; }
        public Nullable<System.DateTime> DateofServiceofNotice { get; set; }
        public Nullable<System.DateTime> DateofReplytoNotice { get; set; }
        public Nullable<System.DateTime> DateofReceivingReply { get; set; }
        public string ModeofReceipt { get; set; }
        public string Rejoinder { get; set; }
        public Nullable<System.DateTime> DateofCreatingRejoinder { get; set; }
        public Nullable<System.DateTime> DateofRejoinder { get; set; }
        public string ModeofDeliveryofRejoinder { get; set; }
        public string NoticeTitle { get; set; }
        public string RejoinderAddressedto { get; set; }
        public string AddresseeAddress { get; set; }
        public string OtherDetailsofAddressee { get; set; }
        public string NoticeandReplyReference { get; set; }
        public string RejoinderSubject { get; set; }
        public string CreateRejoinder { get; set; }
        public string RejoinderThrough { get; set; }
        public Nullable<System.DateTime> DateofDelivery { get; set; }
        public Nullable<System.DateTime> DateofReceipt { get; set; }
        public int RejoinderNoticeID { get; set; }
    }
}
