//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblReplyToNotice
    {
        public string CaseStatus { get; set; }
        public string NoticeType { get; set; }
        public string StatutoryProvision { get; set; }
        public string NoticeReceivedbyClient { get; set; }
        public string NoticeBroughtbyClientforReply { get; set; }
        public Nullable<System.DateTime> ReplytoNoticeCreatedOn { get; set; }
        public Nullable<System.DateTime> DateofReply { get; set; }
        public string ModeofServiceandDelivery { get; set; }
        public string ReplyAddressedto { get; set; }
        public string AddresseeAddress { get; set; }
        public string OtherDetailsofAddressee { get; set; }
        public string RespondentsName { get; set; }
        public string RespondentsAddress { get; set; }
        public string NoticeTitle { get; set; }
        public string OtherDetailsofRespondent { get; set; }
        public string NoticeReference { get; set; }
        public string ReplySubject { get; set; }
        public string CreateReply { get; set; }
        public string ReplyThrough { get; set; }
        public Nullable<System.DateTime> DateofDelivery { get; set; }
        public Nullable<System.DateTime> DateofReceipt { get; set; }
        public int ReplyNoticeID { get; set; }
    }
}
