//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRegOtp
    {
        public System.Guid Id { get; set; }
        public string Mobile { get; set; }
        public string otpvalue { get; set; }
        public Nullable<int> isactive { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<int> isLogin { get; set; }
    }
}
