//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserCas
    {
        public int iid { get; set; }
        public string vCaseType { get; set; }
        public string vCaseNo { get; set; }
        public string vCaseYear { get; set; }
        public string DiaryNo { get; set; }
        public string vCourt { get; set; }
        public Nullable<System.DateTime> dEntryDate { get; set; }
        public string vusername { get; set; }
        public Nullable<int> iflag { get; set; }
        public string vBench { get; set; }
        public string vside { get; set; }
        public string vCourtTitle { get; set; }
        public string vStampReg { get; set; }
        public string vAdd { get; set; }
        public Nullable<long> matterid { get; set; }
        public string casedetail { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
    }
}
