//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserCasesMapCaseStatusMaster
    {
        public System.Guid id { get; set; }
        public long UserCaseId { get; set; }
        public Nullable<System.Guid> MatterID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
        public string UserId { get; set; }
        public Nullable<int> IsRevenueCourt { get; set; }
        public Nullable<int> IsReraCourt { get; set; }
    }
}
