//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWFEvent
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> WorkFlowId { get; set; }
        public string EventName { get; set; }
        public string EventDescription { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
    }
}
