//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWfStatustask
    {
        public int id { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string StatusText { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
    }
}
