//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWFstate1Form
    {
        public long id { get; set; }
        public Nullable<int> Stage { get; set; }
        public Nullable<long> WorkFlowId { get; set; }
        public Nullable<int> Formid { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Users { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
    }
}
