//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkflowTaskStateColMap
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> TaskId { get; set; }
        public Nullable<System.Guid> Stageid { get; set; }
        public string ColumnNo { get; set; }
        public string ColumnName { get; set; }
        public Nullable<int> stage { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
    }
}
