//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimerList
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> tcontact { get; set; }
        public Nullable<System.Guid> tmatter { get; set; }
        public string titem { get; set; }
        public Nullable<System.DateTime> tdate { get; set; }
        public string callDura { get; set; }
        public string tdetails { get; set; }
        public Nullable<bool> tbill { get; set; }
        public Nullable<System.Guid> tbillby { get; set; }
        public Nullable<long> hrrate { get; set; }
        public Nullable<long> total { get; set; }
        public string tprivnotes { get; set; }
        public Nullable<System.Guid> userid { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string stime { get; set; }
        public string etime { get; set; }
        public Nullable<int> iupload { get; set; }
        public Nullable<int> iupdate { get; set; }
        public Nullable<System.Guid> Firmid { get; set; }
        public Nullable<int> IsSync { get; set; }
        public Nullable<int> TimeEntryType { get; set; }
        public Nullable<int> Ischangewip { get; set; }
        public Nullable<int> Isbilling { get; set; }
    }
}
